from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import simulator


def run_simulator_limited(output_path: str | Path, batches: int) -> dict:
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    vessels = copy.deepcopy(simulator.VESSELS)

    batches_written = 0
    items_written = 0

    with output_file.open("w", encoding="utf-8", newline="\n") as handle:
        for index in range(batches):
            vessel = vessels[index % len(vessels)]
            batch = vessel.make_batch()
            handle.write(json.dumps(batch) + "\n")
            batches_written += 1
            items_written += len(batch.get("items", []))

    return {
        "batches_written": batches_written,
        "items_written": items_written,
        "note": "Batches were generated by importing simulator.VESSELS and calling make_batch() without entering the infinite loop.",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a limited number of simulator batches into JSONL.")
    parser.add_argument("--output", required=True, help="Output JSONL file.")
    parser.add_argument("--batches", required=True, type=int, help="Number of batches to generate.")
    args = parser.parse_args()

    summary = run_simulator_limited(args.output, args.batches)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
