from __future__ import annotations

import argparse
import copy
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import simulator


def run_simulator_limited(
    output_path: str | Path,
    batches: int,
    *,
    profile: str = "default",
    reset_output: bool = False,
    seed: int | None = None,
    vessels: int | None = None,
    records_per_vessel: int | None = None,
    repeat_state_buckets: bool = False,
) -> dict:
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    vessel_count = max(int(vessels or len(simulator.VESSELS)), 1)
    batches_to_write = max(int(records_per_vessel or 0) * vessel_count, int(batches))
    active_vessels = _build_demo_vessels(vessel_count)
    rng = random.Random(seed)

    _configure_demo_environment()
    _apply_profile(active_vessels, profile, rng)

    batches_written = 0
    items_written = 0
    vessel_modes: dict[str, int] = {}
    vessel_ids: set[str] = set()

    if reset_output and output_file.exists():
        output_file.unlink()

    file_mode = "a" if output_file.exists() and not reset_output else "w"
    with output_file.open(file_mode, encoding="utf-8", newline="\n") as handle:
        for index in range(batches_to_write):
            vessel = active_vessels[index % len(active_vessels)]
            if profile == "sea-passage" and repeat_state_buckets:
                _prepare_vessel_for_sea_passage(vessel, rng, pattern_index=index % 4)
            batch = vessel.make_batch()
            handle.write(json.dumps(batch) + "\n")
            batches_written += 1
            items_written += len(batch.get("items", []))
            for item in batch.get("items", []):
                vessel_ids.add(str(item.get("node_id") or item.get("imo_number") or item.get("vessel_name") or "unknown"))
                mode = str(item.get("vessel_mode") or "unknown")
                vessel_modes[mode] = vessel_modes.get(mode, 0) + 1

    return {
        "batches_written": batches_written,
        "items_written": items_written,
        "profile": profile,
        "seed": seed,
        "vessels_requested": vessel_count,
        "vessels_used": len(vessel_ids) or len(active_vessels),
        "records_per_vessel": records_per_vessel,
        "repeat_state_buckets": repeat_state_buckets,
        "vessel_modes": vessel_modes,
        "note": "Batches were generated by importing simulator.VESSELS and calling make_batch() without entering the infinite loop.",
    }


def _configure_demo_environment() -> None:
    # Keep limited runs deterministic and offline-friendly.
    simulator.SIMULATOR_OFFLINE_MODE = True
    simulator.fetch_weather = simulator.deterministic_demo_weather


def _apply_profile(vessels: list, profile: str, rng: random.Random) -> None:
    if profile == "default":
        for index, vessel in enumerate(vessels):
            if hasattr(vessel, "rng") and seedable_rng(vessel):
                vessel.rng.seed(rng.randint(0, 10_000_000) + index)
        return
    if profile != "sea-passage":
        raise ValueError(f"Unsupported profile: {profile}")

    for index, vessel in enumerate(vessels):
        if hasattr(vessel, "rng") and seedable_rng(vessel):
            vessel.rng.seed(rng.randint(0, 10_000_000) + index)
        _prepare_vessel_for_sea_passage(vessel, rng, pattern_index=index)


def _prepare_vessel_for_sea_passage(vessel, rng: random.Random, pattern_index: int = 0) -> None:
    speed_target, progress_target, cargo_band = _sea_passage_pattern(pattern_index)
    if hasattr(vessel, "route_coords") and len(vessel.route_coords) >= 4:
        vessel.leg_index = _select_open_sea_leg_index(vessel)
        vessel.leg_progress = progress_target
    else:
        vessel.leg_index = 0
        vessel.leg_progress = progress_target

    vessel.vessel_mode = getattr(simulator, "MODE_STEAMING", "Steaming")
    vessel.anchor_locked = False
    vessel.drag_anchor_active = False
    vessel.commanded_through_water_speed_kn = _sea_speed_target(vessel, speed_target)
    vessel.actual_through_water_speed_kn = max(vessel.commanded_through_water_speed_kn - 0.2, 10.8)
    vessel.speed_jitter = 0.0
    vessel.lagged_required_power_kw = max(float(getattr(vessel, "installed_power_kw", 0.0)) * 0.45, 0.0)
    vessel.lagged_rpm = sum(getattr(vessel, "rpm_range_steaming", (60, 80))) / 2.0
    vessel.main_engine_running_last_step = True

    if hasattr(vessel, "sea_speed_min"):
        vessel.sea_speed_min = max(float(vessel.sea_speed_min), 11.0)
    if hasattr(vessel, "sea_speed_max"):
        vessel.sea_speed_max = max(float(vessel.sea_speed_max), 13.5)
    if hasattr(vessel, "speed_control_integral"):
        vessel.speed_control_integral = 0.0
    if hasattr(vessel, "speed_control_prev_error"):
        vessel.speed_control_prev_error = 0.0
    if hasattr(vessel, "governor_integral"):
        vessel.governor_integral = 0.0
    if hasattr(vessel, "governor_prev_error"):
        vessel.governor_prev_error = 0.0

    # Bias the vessel away from extreme ballast-like idle states without changing class defaults.
    if hasattr(vessel, "cargo_quantity") and hasattr(vessel, "cargo_max"):
        cargo_floor = float(getattr(vessel, "cargo_max", 0.0)) * cargo_band[0]
        cargo_ceiling = float(getattr(vessel, "cargo_max", 0.0)) * cargo_band[1]
        if cargo_ceiling > 0:
            vessel.cargo_quantity = round(rng.uniform(cargo_floor, cargo_ceiling), 2)


def _build_demo_vessels(vessel_count: int) -> list:
    base_vessels = copy.deepcopy(simulator.VESSELS)
    if vessel_count <= len(base_vessels):
        return base_vessels[:vessel_count]

    expanded_vessels = base_vessels[:]
    template_count = len(base_vessels)
    for index in range(template_count, vessel_count):
        vessel = copy.deepcopy(base_vessels[index % template_count])
        suffix = f"{index + 1:04d}"
        vessel.name = f"{vessel.name} Demo {index + 1}"
        vessel.node_id = f"NODE-DEMO-{suffix}"
        vessel.gateway_uid = f"GW-DEMO-{suffix}"
        vessel.imo_number = f"99{index + 1:05d}"
        vessel.mmsi = f"98{index + 1:07d}"[:9]
        expanded_vessels.append(vessel)
    return expanded_vessels


def _sea_passage_pattern(pattern_index: int) -> tuple[float, float, tuple[float, float]]:
    patterns = [
        (11.4, 0.40, (0.55, 0.70)),
        (12.2, 0.50, (0.62, 0.78)),
        (12.9, 0.45, (0.68, 0.84)),
        (13.6, 0.55, (0.74, 0.90)),
    ]
    return patterns[pattern_index % len(patterns)]


def _select_open_sea_leg_index(vessel) -> int:
    leg_lengths = list(getattr(vessel, "leg_lengths", []))
    if not leg_lengths:
        return 0

    candidate_indices = list(range(1, max(len(leg_lengths) - 1, 1)))
    if not candidate_indices:
        candidate_indices = list(range(len(leg_lengths)))

    return max(candidate_indices, key=lambda idx: leg_lengths[idx])


def _sea_speed_target(vessel, fallback: float) -> float:
    speed_min = float(getattr(vessel, "sea_speed_min", fallback))
    speed_max = float(getattr(vessel, "sea_speed_max", fallback + 1.0))
    return round(max(speed_min + 0.3, min(speed_max - 0.2, fallback)), 2)


def seedable_rng(vessel) -> bool:
    return hasattr(vessel, "rng") and hasattr(vessel.rng, "seed")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a limited number of simulator batches into JSONL.")
    parser.add_argument("--output", required=True, help="Output JSONL file.")
    parser.add_argument("--batches", required=True, type=int, help="Number of batches to generate.")
    parser.add_argument("--profile", default="default", choices=["default", "sea-passage"], help="Runner profile.")
    parser.add_argument("--reset-output", action="store_true", help="Delete the existing output file before writing.")
    parser.add_argument("--seed", type=int, help="Optional seed for the demo runner.")
    parser.add_argument("--vessels", type=int, help="Optional number of vessels to cycle through.")
    parser.add_argument("--records-per-vessel", type=int, help="Optional batch count per vessel; overrides total batches upward when larger.")
    parser.add_argument("--repeat-state-buckets", action="store_true", help="Re-apply sea-passage setup before each batch to improve repeated bucket coverage.")
    args = parser.parse_args()

    summary = run_simulator_limited(
        args.output,
        args.batches,
        profile=args.profile,
        reset_output=args.reset_output,
        seed=args.seed,
        vessels=args.vessels,
        records_per_vessel=args.records_per_vessel,
        repeat_state_buckets=args.repeat_state_buckets,
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
